services:
  teamspeak:
    build:
      dockerfile: Dockerfile
      context: Docker/TeamSpeak
    container_name: ts3-idle
    ports:
      - 9987:9987/udp
      # - 10011:10011 # RAW Serverquery Port
      - 30033:30033
      - 10080:10080 # HTTP Serverquery Port
    environment:
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept

